# -*- coding: utf-8 -*-
"""KoBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GbQY4iM_50TvEa-2P8LotGEfXof1NvH
"""

import torch
from torch import nn
import numpy as np
import pandas as pd
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# BERT 모델
from transformers import BertTokenizer,BertForSequenceClassification
#GPU 사용
#device = torch.device("cuda")

tokenizer = BertTokenizer.from_pretrained("monologg/kobert")
model = BertForSequenceClassification.from_pretrained("monologg/kobert", num_labels=2)

data=[ "임대인은 계약 기간 동안 임차인의 거주를 보장한다.",
      "임차인은 계약 종료 1개월 전 계약 갱신 여부를 통보한다.",
       "임차인의 요청이 있을 경우 임대인은 집 내부 점검을 사전 고지 후 진행한다.",
       "임차인은 집 내부 수리를 임대인 동의 하에 진행할 수 있다.",
       "계약 해지 시 임차인은 잔여 기간 정산 후 보증금을 반환받는다.",
"임대차 기간 중 건물이 매각되더라도 임차인의 거주 권리는 보장된다.",
       "현시설상태의 주택임대차계약이며, 시설물 파손시 임차인은 원상복구한다.",
       "임대차 계약은 상호 협의 하에 연장할 수 있다.",
"임대인은 계약 종료 후 7일 이내 보증금을 반환한다.",
"임대차 관련 분쟁은 협의 또는 중재 절차를 따른다.",
"임차인은 전입신고와 확정일자를 받을 수 있다.",
    "임대인은 계약 기간 중 집을 무단 출입하지 않는다.",
    "계약서 변경 시 양 당사자의 서명이 필요하다.",
    "임대차 계약은 표준 임대차 계약서를 기준으로 한다.",
    "임대인은 계약 이행에 필요한 서류를 제공한다.",

      "임대인은 보증금을 지급하지 않고 입주를 요구한다.",
      "임대인은 계약서 작성 없이 구두로 계약을 체결한다.",
      "임대인은 전세권 설정을 하지 않는다.",
      "계약 기간 중 건물이 매각될 경우 임차인은 즉시 퇴거한다.",
      "보증금 반환은 임대인이 사정이 되는 대로 지급한다.",
      "임대인은 필요 시 계약을 일방적으로 해지할 수 있다.",
      "임차인은 조기 퇴거 시 잔여 기간 월세를 모두 납부한다."
      "임대인은 보증금 반환을 2년 후에 한다.",
      "계약 기간 중 건물이 매각될 경우 임차인은 즉시 퇴거한다.",
      "계약 해지 사유 발생 시 통보 없이 계약 무효 처리한다.",
      "임차인은 전입신고를 할 수 없다.",
      "임차인은 수리비 전액을 부담한다.",
      "임대인은 임차인 동의 없이 집을 방문할 수 있다.",
       "임차인은 계약 기간 중 모든 수리·리모델링 비용을 부담한다.",
       "임대인은 필요 시 계약을 일방적으로 해지할 수 있다."
       ]
labels=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]


class ContractDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=64):
        self.texts = texts #문장 리스트 (계약 조항 문장들)
        self.labels = labels # 각 문장의 정답 레이블
        self.tokenizer = tokenizer # 텍스트를 숫자로 바꾸는 토크나이저
        self.max_len = max_len # 각 입력 문장의 최대 길이

    def __len__(self):
        return len(self.texts) # 데이터셋의 전체 샘플 수

    #모델이 데이터를 하나씩 가져갈 때 호출
    #idx texts, labels에서 해당 위치의 문장과 라벨을 가져감
    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'labels': torch.tensor(label, dtype=torch.long)
        }


dataset=ContractDataset(data,labels,tokenizer,max_len=64)
train_loader=DataLoader(dataset,batch_size=32,shuffle=True)

from torch.optim import AdamW
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = AdamW(model.parameters(), lr=3e-5)
epochs = 20

for epoch in range(epochs):
    model.train()
    loop = tqdm(train_loader, leave=True)
    for batch in loop:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        loop.set_description(f'Epoch {epoch+1}')
        loop.set_postfix(loss=loss.item())

def predict(text):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", max_length=64, truncation=True, padding='max_length')
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        predicted_class = torch.argmax(logits, dim=1).item()
    return predicted_class

# 테스트할 문장들
test_sentences = [
    "계약 해지 시 임차인은 잔여 기간 정산 후 보증금을 반환받는다.",
    "임대차 기간 중 건물이 매각되더라도 임차인의 거주 권리는 보장된다.",
    "임대인은 전세권 설정을 하지 않는다.",
    "임대인은 계약 종료 후 7일 이내 보증금을 반환한다.",
    "계약서 내용은 양 당사자의 동의를 통해 수정할 수 있다.",
    "계약서 내용 수정은 불가능하다."
]

# 결과 출력
for sentence in test_sentences:
    result = predict(sentence)
    print(f"입력 문장: {sentence}")
    print("사기" if result == 1 else "정상")
    print("-" * 50)