agent.key=6e427a636e6361723130354547546359
agent.url1=http://openapi.seoul.go.kr:8088/
agent.url2=/json/landBizInfo/

map.key=086b1f966a8f9d22e6b32b67ad24a5bc
map.url=https://dapi.kakao.com/v2/local/search/address.json?query=